### ISSUE TITLE
endAlarm should print resolved message

### ISSUE THREAD

**Issue by ryanseys** [melari/RationalBlowsIssues#21]
When the alarm is sounding and the security alarm is resolved then we should print that the alarm has been resolved.

**Comment by melari** [comment]
In this same transition, we also need to turn the alarms off, and disable the sensors. There's currently no action code at all

**Comment by melari** [comment]
For the unit tests I have assumed that the zone controller will be sending a security event of type 'r' (for resolve) to the central controller and that central controller interprets to be the message "A security zone alarm has been resolved"

please either use the above type and message, or update the unit test description in the final report.

**Comment by ryanseys** [comment]
:+1:
