### ISSUE TITLE
Sensors should self test

### ISSUE THREAD

**Issue by melari** [melari/RationalBlowsIssues#4]
Sensors will test themselves when receiving the "arm" message from the zone controller. If they successfully self test, they transition to the "armed" state. If self test fails, the sensor should send a message back to the zone controller to let it know self test failed. This should be passed up to the central controller as a SecurityEvent for logging in the printer and database

**Comment by TrangPham** [comment]
They now selfTest using a conditional thingy. See Update 15

Unit tests:
Should arm if functional
1. run code
2. open state monitor for the sensor 0 on security zone 0
3. inject "arm" into probe "0/toZone/securityZoneR1:0/sensor:0_Probe"
4. sensor should be in armed state

Should not arm if non functional
1. run code
2. open state monitor for the sensor 0 on security zone 0
3. inject "breakSensor" into probe "0/SensorTestPort/securityZoneR1:0/sensor:0_Probe"
4. see that state monitor showed breakSensor transiiton highlighted
5. inject "arm" into probe "0/toZone/securityZoneR1:0/sensor:0_Probe"
6. sensor should be in disarmed state
7. see that the state monitor has False transition highlighted

**Comment by ryanseys** [comment]
Update 14 right?

**Comment by TrangPham** [comment]
Nope 15 - the 14 is the stuff you just completed - I just uploaded the Update 15 Zip and I've updated the final report to include those two test cases as unit tests for the sensor

**Comment by melari** [comment]
:shit:

**Comment by ryanseys** [comment]
How do we run self test? Do we have to run the test manually? Seems right now the "test" is just looking at the functional flag right now and if its true then arming, else it keeps the sensor disarmed. There is `testSensor` message that is currently unused. I'm wondering how we are going to use that or if it should be removed. Going to re-open until we come to consensus on how self test should work.

Also no logging is present, so that will have to be fixed too.

**Comment by TrangPham** [comment]
Logging works. Should only log when it's not functional and doesn't arm. Would not log when it's functional. Yeah that signal should be removed. I did it the way you guys said. Every sensor does the self text on itself

**Comment by TrangPham** [comment]
We don't run "selfTest" manually. But we run the unit tests on it manually like the unit and integration tests on everything else

**Comment by ryanseys** [comment]
Sorry, moved the print action into the transition actions for clarity.

**Comment by ryanseys** [comment]
I've added a `fixSensor` on the TestSensorProtocol so we can set the sensor to functional again without restarting. Also added self transitions on disarmed and armed states for `arm` and `disarm` messages so we don't see errors in the console. Sorry for confusion.
